# SPDX-License-Identifier: Apache-2.0
#

version: '3'

services:
  node:
    image: hyperledger/${IROHA_IMG}
    ports:
      - "50051:50051"
    environment:
      - KEY=node0
      - IROHA_POSTGRES_HOST=iroha_postgres_1
      - IROHA_POSTGRES_PORT=5432
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - ${PWD}/example:/opt/iroha/config
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha/config
    depends_on:
      - postgres

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=HelloW0rld

volumes:
  ccache-data:
