# Copyright Takeshi Yonezu. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3'

services:
  node:
    image: hyperledger/${IROHA_IMG}
    ports:
      - "50051:50051"
    environment:
      - key=node0
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - ${PWD}/example:/opt/iroha/config
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    entrypoint: >
      bash -c "sleep 5;
      /usr/bin/irohad --config config/iroha.conf
      --genesis_block config/genesis.block
      --keypair_name config/node0"
    depends_on:
      - postgres

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=HelloW0rld

volumes:
  ccache-data:
