version: '3'

services:

  node1:
    image: ${IROHA_PRJ}/${IROHA_IMG}
    container_name: iroha-node-1
    restart: always
    ports:
      - "50051:50051"
    environment:
      - IROHA_HOME=/opt/iroha
      - IROHA_CONF=iroha.conf
      - IROHA_NODEKEY=node1
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - ${PWD}:/opt/iroha/config
      - ${PWD}/iroha1/wsv:/tmp/wsv
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha/config
    entrypoint: /opt/iroha/config/entrypoint.sh

  node2:
    image: ${IROHA_PRJ}/${IROHA_IMG}
    container_name: iroha-node-2
    restart: always
    environment:
      - IROHA_HOME=/opt/iroha
      - IROHA_CONF=iroha.conf
      - IROHA_NODEKEY=node2
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - ${PWD}:/opt/iroha/config
      - ${PWD}/iroha2/wsv:/tmp/wsv
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha/config
    entrypoint: /opt/iroha/config/entrypoint.sh

  node3:
    image: ${IROHA_PRJ}/${IROHA_IMG}
    container_name: iroha-node-3
    restart: always
    environment:
      - IROHA_HOME=/opt/iroha
      - IROHA_CONF=iroha.conf
      - IROHA_NODEKEY=node3
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - ${PWD}:/opt/iroha/config
      - ${PWD}/iroha3/wsv:/tmp/wsv
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha/config
    entrypoint: /opt/iroha/config/entrypoint.sh

  node4:
    image: ${IROHA_PRJ}/${IROHA_IMG}
    container_name: iroha-node-4
    restart: always
    environment:
      - IROHA_HOME=/opt/iroha
      - IROHA_CONF=iroha.conf
      - IROHA_NODEKEY=node4
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - ${PWD}:/opt/iroha/config
      - ${PWD}/iroha4/wsv:/tmp/wsv
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha/config
    entrypoint: /opt/iroha/config/entrypoint.sh

volumes:
  ccache-data:
