# Copyright (c) 2017-2019 Takeshi Yonezu
# All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3'

services:

  node0:
    image: ${IROHA_PRJ}/${IROHA_IMG}
    container_name: iroha-node0
    restart: always
    ports:
      - "50051:50051"
    user: "1000:1000"
    environment:
      - IROHA_HOME=/opt/iroha
      - IROHA_CONF=iroha0.conf
      - IROHA_NODEKEY=node0
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - ${PWD}:/opt/iroha/config
      - ${PWD}/block_store0:/tmp/block_store
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha/config
    entrypoint: /opt/iroha/config/entrypoint.sh
    depends_on:
      - postgres0

  node1:
    image: ${IROHA_PRJ}/${IROHA_IMG}
    container_name: iroha-node1
    restart: always
    user: "1000:1000"
    environment:
      - IROHA_HOME=/opt/iroha
      - IROHA_CONF=iroha1.conf
      - IROHA_NODEKEY=node1
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - ${PWD}:/opt/iroha/config
      - ${PWD}/block_store1:/tmp/block_store
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha/config
    entrypoint: /opt/iroha/config/entrypoint.sh
    depends_on:
      - postgres1

  node2:
    image: ${IROHA_PRJ}/${IROHA_IMG}
    container_name: iroha-node2
    restart: always
    user: "1000:1000"
    environment:
      - IROHA_HOME=/opt/iroha
      - IROHA_CONF=iroha2.conf
      - IROHA_NODEKEY=node2
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - ${PWD}:/opt/iroha/config
      - ${PWD}/block_store2:/tmp/block_store
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha/config
    entrypoint: /opt/iroha/config/entrypoint.sh
    depends_on:
      - postgres2

  node3:
    image: ${IROHA_PRJ}/${IROHA_IMG}
    container_name: iroha-node3
    restart: always
    user: "1000:1000"
    environment:
      - IROHA_HOME=/opt/iroha
      - IROHA_CONF=iroha3.conf
      - IROHA_NODEKEY=node3
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - ${PWD}:/opt/iroha/config
      - ${PWD}/block_store3:/tmp/block_store
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha/config
    entrypoint: /opt/iroha/config/entrypoint.sh
    depends_on:
      - postgres3

  postgres0:
    image: postgres:9.5
    container_name: iroha-postgres0
    restart: always
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=HelloW0rld

  postgres1:
    image: postgres:9.5
    container_name: iroha-postgres1
    restart: always
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=HelloW0rld

  postgres2:
    image: postgres:9.5
    container_name: iroha-postgres2
    restart: always
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=HelloW0rld

  postgres3:
    image: postgres:9.5
    container_name: iroha-postgres3
    restart: always
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=HelloW0rld

volumes:
  ccache-data:
