# Copyright (c) 2017-2019 Takeshi Yonezu
# All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3'

services:
  node:
    image: ${IROHA_PRJ}/${IROHA_IMG}
    restart: always
    ports:
      - "50051:50051"
      - "10001:10001"
    environment:
      - IROHA_HOME=/opt/iroha
      - IROHA_CONF=config.docker
      - IROHA_POSTGRES_HOST=iroha_postgres_1
      - IROHA_POSTGRES_PORT=5432
      - IROHA_NODEKEY=node1
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - ${PWD}:/opt/iroha/config
      - ${PWD}/iroha1/tmp/block_store:/tmp/block_store
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha/config
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=HelloW0rld
    volumes:
      - ${PWD}/iroha1/var/lib/postgresql/data:/var/lib/postgresql/data

volumes:
  ccache-data:
