# Copyright (c) 2017-2019 Takeshi Yonezu
# All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3'

services:
  node:
    image: ${IROHA_PRJ}/${IROHA_IMG}
    restart: always
    ports:
      - "50051:50051"
      - "10001:10001"
    environment:
      - IROHA_HOME=/opt/iroha
      - IROHA_CONF=iroha.conf
      - IROHA_NODEKEY=node1
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - ${PWD}:/opt/iroha/config
      - ${PWD}/iroha1/tmp/wsv:/tmp/wsv
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha/config

volumes:
  ccache-data:
